print("Тестування функцій списків\n")
test_list = [9,8,1]
print("Початковий список:", test_list)
test_list.append(4)
print("append(4)", test_list)
test_list.extend([5,2])
print("extend([5,2])", test_list)
test_list.insert(1,7)
print("insert(1,7)", test_list)
test_list.remove(7)
print("remove(7)", test_list)
test_list.sort()
print("sort()", test_list)
test_list.reverse()
print("reverse()", test_list)
copy_list = test_list.copy()
print("copy()", copy_list)
test_list.clear()
print("clear()", test_list)